<a href="https://colab.research.google.com/github/costpetrides/Computational-Physics/blob/main/LinearSystems/13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Ορισμός του πίνακα A και του διανύσματος b
A = np.array([[1., 1., 1.],
              [4., 3., -1.],
              [3., 5., 3.]])
b = np.array([1., 6., 4.])

n = A.shape[0]  # Μέγεθος συστήματος

# Βήμα 1: Αρχικοποίηση πινάκων L και U
L = np.identity(n)   # Κάτω τριγωνικός με 1 στη διαγώνιο
U = np.zeros((n, n)) # Άνω τριγωνικός

# LU αποσύνθεση (Doolittle)
for i in range(n):
    # Υπολογισμός στοιχείων U[i][j]
    for j in range(i, n):
        sum_u = sum(L[i][k] * U[k][j] for k in range(i))
        U[i][j] = A[i][j] - sum_u

    # Υπολογισμός στοιχείων L[j][i]
    for j in range(i+1, n):
        sum_l = sum(L[j][k] * U[k][i] for k in range(i))
        L[j][i] = (A[j][i] - sum_l) / U[i][i]

print("Πίνακας L:")
print(L)
print("\nΠίνακας U:")
print(U)

# Βήμα 2: Forward substitution για L*y = b
y = np.zeros(n)
for i in range(n):
    sum_ly = sum(L[i][j]*y[j] for j in range(i))
    y[i] = b[i] - sum_ly

print("\nΔιάνυσμα y (λύση L*y=b):")
print(y)

# Βήμα 3: Backward substitution για U*x = y
x = np.zeros(n)
for i in reversed(range(n)):
    sum_ux = sum(U[i][j]*x[j] for j in range(i+1, n))
    x[i] = (y[i] - sum_ux) / U[i][i]

print("\nΤελική λύση x (λύση U*x=y):")
print(x)


Πίνακας L:
[[ 1.  0.  0.]
 [ 4.  1.  0.]
 [ 3. -2.  1.]]

Πίνακας U:
[[  1.   1.   1.]
 [  0.  -1.  -5.]
 [  0.   0. -10.]]

Διάνυσμα y (λύση L*y=b):
[1. 2. 5.]

Τελική λύση x (λύση U*x=y):
[ 1.   0.5 -0.5]
