<a href="https://colab.research.google.com/github/costpetrides/Computational-Physics/blob/main/LinearSystems/13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import sys

In [11]:
A=np.array([[1.,  1., 1.],
            [4., 3., -1.],
            [3., 5., 3.]])

b=np.array([[1.],
            [6.],
            [4.]])



C=np.concatenate((A,b),axis=1)
(n,m)=C.shape


U=A.copy()
L=np.identity(n)

for k in range(n-1):
  for j in range(k+1,n):
    L[j][k]=U[j][k]/U[k][k]
    U[j][k:n]=U[j][k:n]-L[j][k]*U[k][k:n]

print('L matrix')
print(L)

print()

print('U matrix')
print(U)


L matrix
[[ 1.  0.  0.]
 [ 4.  1.  0.]
 [ 3. -2.  1.]]

U matrix
[[  1.   1.   1.]
 [  0.  -1.  -5.]
 [  0.   0. -10.]]


In [13]:
C=np.concatenate((L,b),axis=1)
(n,m)=C.shape

for i in range(n):
  for j in range(n):
    if i!=j:
      ratio=C[j][i]/C[i][i]
      for k in range(m):
        C[j][k]=C[j][k] - ratio*C[i][k]

y=np.zeros(n)

for i in range(n):
  y[i]=C[i][n]/C[i][i]

for i in range(n):
    print('y[%.f]=%.2f' %(i+1,y[i]))

y[1]=1.00
y[2]=2.00
y[3]=5.00


In [14]:

y=np.array([[y[0]],
            [y[1]],
            [y[2]]])

C=np.concatenate((U,y),axis=1)
(n,m)=C.shape

for i in range(n):
  for j in range(n):
    if i!=j:
      ratio=C[j][i]/C[i][i]
      for k in range(m):
        C[j][k]=C[j][k] - ratio*C[i][k]


x=np.zeros(n)

for i in range(n):
  x[i]=C[i][n]/C[i][i]

for i in range(n):
    print('x[%.f]=%.2f' %(i+1,x[i]))

x[1]=1.00
x[2]=0.50
x[3]=-0.50
